{% set version = "0.25.3" %}

package:
  name: pytest-asyncio
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.org/packages/source/p/pytest-asyncio/pytest_asyncio-{{ version }}.tar.gz
    sha256: fc1da2cf9f125ada7e710b4ddad05518d4cee187ae9412e9ac9271003497f07a
  - folder: src
    url: https://github.com/pytest-dev/pytest-asyncio/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 6e804b2a165f28f2a552e73e8ae2efd01f766d58510766dd6dd03be54583cd75

build:
  number: 0
  noarch: python
  script:
    - cd dist
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm >=6.2
  run:
    - pytest >=8.2,<9
    - python >={{ python_min }}

test:
  source_files:
    - src/tests
    - src/setup.cfg
  imports:
    - pytest_asyncio
  requires:
    - pip
    - coverage
    - hypothesis >=5.7.1
    - pytest-trio
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: http://github.com/pytest-dev/pytest-asyncio
  license: Apache-2.0
  license_file: dist/LICENSE
  summary: Pytest support for asyncio
  dev_url: https://github.com/pytest-dev/pytest-asyncio

extra:
  recipe-maintainers:
    - sodre
    - bollwyvl
