{% set name = "pytest-asyncio" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9882c0c6b24429449f5f969a5158b528f39bde47dc32e85b9f0403965017e700

build:
  number: 0
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pytest >=5.4

test:
  imports:
    - pytest_asyncio

about:
  home: http://github.com/pytest-dev/pytest-asyncio
  license: Apache-2.0
  license_file: LICENSE
  #license_file: LICENSE # License file is missing in package
  summary: Pytest support for asyncio

  dev_url: https://github.com/pytest-dev/pytest-asyncio

extra:
  recipe-maintainers:
    - sodre
