{% set version = "0.25.2" %}

package:
  name: pytest-asyncio
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.org/packages/source/p/pytest-asyncio/pytest_asyncio-{{ version }}.tar.gz
    sha256: 3f8ef9a98f45948ea91a0ed3dc4268b5326c0e7bce73892acc654df4262ad45f
  - folder: src
    url: https://github.com/pytest-dev/pytest-asyncio/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 1f3688b80f1ac96e88356b73bb6713e645352b83b11c17f9f8018d368a760b41

build:
  number: 0
  noarch: python
  script:
    - cd dist
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm >=6.2
  run:
    - pytest >=8.2,<9
    - python >={{ python_min }}

test:
  source_files:
    - src/tests
    - src/setup.cfg
  imports:
    - pytest_asyncio
  requires:
    - pip
    - coverage
    - hypothesis >=5.7.1
    - pytest-trio
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: http://github.com/pytest-dev/pytest-asyncio
  license: Apache-2.0
  license_file: dist/LICENSE
  summary: Pytest support for asyncio
  dev_url: https://github.com/pytest-dev/pytest-asyncio

extra:
  recipe-maintainers:
    - sodre
    - bollwyvl
