{% set version = "0.24.0" %}

package:
  name: pytest-asyncio
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.org/packages/source/p/pytest-asyncio/pytest_asyncio-{{ version }}.tar.gz
    sha256: d081d828e576d85f875399194281e92bf8a68d60d72d1a2faf2feddb6c46b276
  - folder: src
    url: https://github.com/pytest-dev/pytest-asyncio/archive/refs/tags/v{{ version }}.tar.gz
    sha256: e770d3d3de20968d03a556c8f2ebe461c568d283a993f4a1179ddd02e5f633a6

build:
  number: 1
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm >=6.2
  run:
    - pytest >=8.2,<9
    - python >={{ python_min }}

test:
  source_files:
    - src/tests
    - src/setup.cfg
  imports:
    - pytest_asyncio
  requires:
    - pip
    - coverage
    - hypothesis >=5.7.1
    - pytest-trio
    - python {{ python_min }}
  commands:
    - pip check
    - cd src
    # the skip is for docker network issues in CI, reduces coverage from 96
    - coverage run --branch -m pytest -vv --color=yes --tb=long -k 'not (unused_port_fixture or unused_port_factory_fixture or auto_mode_cmdline)'
    - coverage report --fail-under=91

about:
  home: http://github.com/pytest-dev/pytest-asyncio
  license: Apache-2.0
  license_file: dist/LICENSE
  summary: Pytest support for asyncio
  dev_url: https://github.com/pytest-dev/pytest-asyncio

extra:
  recipe-maintainers:
    - jjerphan
    - sodre
    - bollwyvl
